[package]
name = "autd3-emulator"
description = "autd3 emulator for calculating sound field, emulation of firmware, etc"
readme = "README.md"
keywords = ["autd"]
version = "38.0.1"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2024"
license = "MIT"
repository = "https://github.com/shinolab/autd3-emulator"

[package.metadata.docs.rs]
features = ["gpu"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["use_nalgebra", "polars", "parallel"]
polars = ["dep:polars"]
gpu = ["wgpu", "bytemuck"]
parallel = ["rayon"]
use_nalgebra = ["autd3/use_nalgebra", "autd3-core/use_nalgebra"]

[dependencies]
autd3 = { version = "38.0.1", default-features = false }
autd3-core = { version = "38.0.1", default-features = false, features = ["link", "firmware"] }
autd3-firmware-emulator = { version = "38.0.1", default-features = false }
bytemuck = { version = "1.25.0", optional = true, default-features = false }
polars = { version = "0.54.4", optional = true, features = ["dtype-u16", "dtype-u8"], default-features = false }
rayon = { version = "1.10.0", optional = true, default-features = false }
wgpu = { version = "30.0.0", optional = true, default-features = false, features = ["std", "parking_lot", "dx12", "vulkan", "metal", "wgsl"] }

[dev-dependencies]
autd3 = { version = "38.0.1", default-features = false, features = ["gain", "modulation"] }
approx = { version = "0.5.1", default-features = false }
polars = { version = "0.54.4", default-features = false, features = ["csv", "fmt"] }
rand = { version = "0.10.0", default-features = false, features = ["thread_rng"] }
rstest = { version = "0.26.1", default-features = false }
textplots = { version = "0.8.7", default-features = false }
itertools = { version = "0.15.0", default-features = false }
